apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: ghcr.io/renovatebot/charts
    chart: renovate
    targetRevision: 46.251.0
    helm:
      values: |
        cronjob:
          schedule: "0 14 * * *"
          
        envList:
          - name: RENOVATE_TOKEN
            valueFrom:
              secretKeyRef:
                name: renovate-token
                key: token
                
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 512Mi

        renovate:
          config: |
            {
              "platform": "github",
              "extends": ["config:recommended"],
              "repositories": ["GiannisStathoudakis/TheOneLab"],
              "argocd": {
                "fileMatch": ["\\.yaml$"]
              },
              "packageRules": [
                {
                  "description": "Block all major updates",
                  "matchUpdateTypes": ["major"],
                  "enabled": false
                },
                {
                  "description": "Group minor and patch updates",
                  "matchUpdateTypes": ["minor", "patch"],
                  "groupName": "Non-Major Dependency Updates"
                }
              ]
            }
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true