apiVersion: external-secrets.io/v1 
kind: ExternalSecret
metadata:
  name: envoy-oidc-es
  namespace: kube-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: envoy-oidc-secret
  data:
  - secretKey: client-secret
    remoteRef:
      key: secret/envoy-gateway
      property: clientSecret