apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.redpanda.com
    chart: redpanda
    targetRevision: 26.2.4
    helm:
      values: |
        statefulset:
          replicas: 1
        
        resources:
          cpu:
            cores: 1
          memory:
            container:
              max: 2.5Gi
              
        tls:
          enabled: false

        auth:
          sasl:
            enabled: false
            
        storage:
          persistentVolume:
            enabled: true
            storageClass: openebs-lvm
            size: 5Gi
            
        tuning:
          tune_aio_events: false
        
        # Uncomment this block ONLY if Tempo is the exclusive user of Redpanda
        #config:
        #  cluster:
        #    log_retention_ms: 3600000 # 1hour
        #    retention_bytes: 2147483648 # Delete data if partition exceeds 2GB to prevent disk full issues

  destination:
    server: https://kubernetes.default.svc
    namespace: redpanda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true