apiVersion: external-secrets.io/v1 
kind: ExternalSecret
metadata:
  name: mimir-s3-credentials
  namespace: mimir
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mimir-s3-credentials
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: secret/mimir
      property: access-key
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: secret/mimir
      property: secret-key