apiVersion: v1
kind: Namespace
metadata:
  name: spring-apps
  labels:
    # Block root users, privilege escalation, etc.
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    # Warning if someone even tries
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest