apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: ecommerce
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: ecommerce-images
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/GiannisStathoudakis/springboot-kafka-streams-microservices-demo.git
            checkout:
              branch: master
        - uses: git-clear
        - uses: helm-update-image
          config:
            path: chart/values.yaml
            images:
              - image: ghcr.io/giannisstathoudakis/ms-orders
                key: microservices.orders.tag
                value: Tag
              - image: ghcr.io/giannisstathoudakis/ms-payment
                key: microservices.payment.tag
                value: Tag
              - image: ghcr.io/giannisstathoudakis/ms-stock
                key: microservices.stock.tag
                value: Tag
        - uses: git-commit
          config:
            messageFromSteps: helm-update-image
        - uses: git-push