apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |-
    nodelocal:
      enabled: true
      extraClusterDomains:
        - kublab.org

    zoneFiles:
      - filename: kublab.org.conf
        domain: kublab.org
        contents: |
          kublab.org:53 {
            errors
            cache 30
            template IN A kublab.org {
              match ".*\\.kublab\.org$"
              answer "{{ .Name }} 60 IN A 10.17.3.100"
            }
            forward . 1.1.1.1 8.8.8.8
          }