apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aquasecurity.github.io/helm-charts/
    chart: trivy-operator
    targetRevision: 0.34.0
    helm:
      values: |
        operator:
          scanJobsConcurrentLimit: 1
                   
          metricsVulnIdEnabled: true
          metricsConfigAuditInfo: true
          metricsExposedSecretInfo: true
          metricsRbacAssessmentInfo: true
          metricsInfraAssessmentInfo: true
          metricsClusterComplianceInfo: true
          metricsImageInfo: true
                        
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "80"
            prometheus.io/path: "/metrics"
          
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true