---
apiVersion: external-secrets.io/v1 
kind: ExternalSecret
metadata:
  name: defectdojo-core-es
  namespace: defectdojo
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: defectdojo
  data:
  - secretKey: DD_SECRET_KEY
    remoteRef:
      key: secret/defectdojo
      property: djangoSecretKey
  - secretKey: DD_CREDENTIAL_AES_256_KEY
    remoteRef:
      key: secret/defectdojo
      property: djangoCredentialKey
  - secretKey: METRICS_HTTP_AUTH_PASSWORD
    remoteRef:
      key: secret/defectdojo
      property: djangoSecretKey

---
apiVersion: external-secrets.io/v1 
kind: ExternalSecret
metadata:
  name: defectdojo-pg-es
  namespace: defectdojo
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: defectdojo-postgresql-specific
  data:
  - secretKey: postgresql-password
    remoteRef:
      key: secret/defectdojo
      property: dbPassword
  - secretKey: postgresql-postgres-password
    remoteRef:
      key: secret/defectdojo
      property: dbPassword

---
apiVersion: external-secrets.io/v1 
kind: ExternalSecret
metadata:
  name: defectdojo-valkey-es
  namespace: defectdojo
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: defectdojo-valkey-specific
  data:
  - secretKey: valkey-password
    remoteRef:
      key: secret/defectdojo
      property: valkeyPassword

---
apiVersion: external-secrets.io/v1 
kind: ExternalSecret
metadata:
  name: defectdojo-oidc-es
  namespace: defectdojo
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: defectdojo-oidc-secret
  data:
  - secretKey: clientID
    remoteRef:
      key: secret/defectdojo
      property: clientId
  - secretKey: clientSecret
    remoteRef:
      key: secret/defectdojo
      property: clientSecret