apiVersion: external-secrets.io/v1 
kind: ExternalSecret
metadata:
  name: defectdojo-eso-secrets
  namespace: defectdojo
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: defectdojo-core-secrets
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: defectdojo
  data:
  - secretKey: clientSecret
    remoteRef:
      key: secret/defectdojo
      property: clientSecret
  - secretKey: clientID
    remoteRef:
      key: secret/defectdojo
      property: clientId
  - secretKey: dbPassword
    remoteRef:
      key: secret/defectdojo
      property: dbPassword
  - secretKey: valkeyPassword
    remoteRef:
      key: secret/defectdojo
      property: valkeyPassword
  - secretKey: djangoSecretKey
    remoteRef:
      key: secret/defectdojo
      property: djangoSecretKey
  - secretKey: djangoCredentialKey
    remoteRef:
      key: secret/defectdojo
      property: djangoCredentialKey