apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: defectdojo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/helm-charts
    chart: defectdojo
    targetRevision: 1.9.52 
    helm:
      values: |
        host: defectdojo.kublab.org
        siteUrl: "https://defectdojo.kublab.org"
        
        alternativeHosts:
          - defectdojo-django.defectdojo.svc.cluster.local
          
        django:
          ingress:
            enabled: false
          uwsgi:
            replicas: 1
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 1024Mi

        celery:
          worker:
            replicas: 1
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
          beat:
            replicas: 1

        postgresql:
          enabled: true
          architecture: standalone
          auth:
            username: defectdojo
            database: defectdojo
          primary:
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi

        valkey:
          enabled: true
          architecture: standalone
          primary:
            resources:
              limits:
                memory: 128Mi

        initializer:
          run: true
          keepSeconds: 60
          
        admin:
          user: admin
          mail: admin@kublab.org        
  destination:
    server: https://kubernetes.default.svc
    namespace: defectdojo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true