---
apiVersion: v1
kind: Service
metadata:
  name: rke2-coredns-upstream
  namespace: kube-system
spec:
  ports:
  - name: udp-53
    port: 53
    protocol: UDP
    targetPort: 53
  - name: tcp-53
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    app.kubernetes.io/instance: rke2-coredns
    app.kubernetes.io/name: rke2-coredns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-local-dns-ebpf
  namespace: kube-system
data:
  Corefile: |
    cluster.local:53 {
      log
      errors
      cache 30
      reload
      loop
      bind 0.0.0.0
      forward . {$RKE2_COREDNS_UPSTREAM_SERVICE_HOST} {
        force_tcp
      }
      prometheus :9253
    }
    
    kublab.org:53 {
      log
      errors
      cache 30
      reload
      loop
      bind 0.0.0.0
      forward . {$RKE2_COREDNS_UPSTREAM_SERVICE_HOST} {
        force_tcp
      }
      prometheus :9253
    }

    .:53 {
      log
      errors
      cache 30
      reload
      loop
      forward . 1.1.1.1 8.8.8.8
      prometheus :9253
    }

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-local-dns-ebpf
  namespace: kube-system

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-local-dns-ebpf
  namespace: kube-system
  labels:
    k8s-app: node-local-dns-ebpf
spec:
  selector:
    matchLabels:
      k8s-app: node-local-dns-ebpf
  template:
    metadata:
      labels:
        k8s-app: node-local-dns-ebpf
    spec:
      serviceAccountName: node-local-dns-ebpf
      containers:
      - name: coredns-cache
        image: registry.k8s.io/coredns/coredns:v1.14.6
        args: [ "-conf", "/etc/Corefile" ]
        ports:
        - containerPort: 53
          name: udp-53
          protocol: UDP
        - containerPort: 53
          name: tcp-53
          protocol: TCP
        - containerPort: 9253
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/Corefile
          name: config-volume
          subPath: Corefile
      volumes:
      - name: config-volume
        configMap:
          name: node-local-dns-ebpf
          items:
          - key: Corefile
            path: Corefile

---
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: nodelocaldns-ebpf
  namespace: kube-system
spec:
  redirectFrontend:
    serviceMatcher:
      serviceName: rke2-coredns-rke2-coredns
      namespace: kube-system
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns-ebpf
    toPorts:
      - name: udp-53
        port: "53"
        protocol: UDP
      - name: tcp-53
        port: "53"
        protocol: TCP
  skipRedirectFromBackend: true