apiVersion: v1
kind: Service
metadata:
  name: technitium-service
  namespace: dns
spec:
  type: ClusterIP
  ClusterIP: 10.43.238.5
  selector:
    app: technitium
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: web-ui
      port: 5380
      targetPort: 5380
      protocol: TCP