---
- hosts: master
  tasks:
    - name: 01. Apply Application
      kubernetes.core.k8s:
        state: present
        src: "https://raw.githubusercontent.com/GiannisStathoudakis/TheOneLab/master/Bootstrap/kargo-root.yaml?v=5"