---
- name: Configure CoreDNS for Technitium Routing
  hosts: master
  become: true
  tasks:
    - name: Copy CoreDNS HelmChartConfig
      ansible.builtin.copy:
        src: configure-coredns.yaml
        dest: /var/lib/rancher/rke2/server/manifests/rke2-coredns-config.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Wait for RKE2 Helm Controller to process the manifest
      ansible.builtin.pause:
        seconds: 15

    - name: Restart CoreDNS
      ansible.builtin.command:
        cmd: /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml rollout restart deployment rke2-coredns-rke2-coredns -n kube-system
      register: rollout_status
      changed_when: true

    - name: Show rollout status
      ansible.builtin.debug:
        var: rollout_status.stdout