---
- hosts: master
  vars_files:
    - files/cluster-keys.json

  tasks:
    - name: 01. Unlock Vault
      ansible.builtin.shell: |
        kubectl exec -i -n vault vault-0 -- sh -s << EOF
        vault operator unseal {{ item }}
        EOF
      loop: "{{ unseal_keys_b64[0:3] }}"
      no_log: true
      changed_when: false