apiVersion: external-secrets.io/v1 
kind: ExternalSecret
metadata:
  name: kyverno-cosign-secret
  namespace: kyverno
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kyverno-cosign-secret
  data:
  - secretKey: cosign.pub
    remoteRef:
      key: secret/cosign
      property: public_key