apiVersion: external-secrets.io/v1 
kind: ExternalSecret
metadata:
  name: trivy-dojo-eso
  namespace: defectdojo-report
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: trivy-dojo-credentials
  data:
  - secretKey: defectdojo-api-key
    remoteRef:
      key: secret/defectdojo
      property: dojoApiKey